/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as MyQuotesRouteImport } from './routes/my-quotes'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FollowRouteImport } from './routes/follow'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeddingsIndexRouteImport } from './routes/weddings.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WeddingsWinterClevelandOhioRouteImport } from './routes/weddings.winter-cleveland-ohio'
import { Route as WeddingsSpringAuroraOhioRouteImport } from './routes/weddings.spring-aurora-ohio'
import { Route as WeddingsFallHudsonOhioRouteImport } from './routes/weddings.fall-hudson-ohio'
import { Route as WeddingsBookingTimelineRouteImport } from './routes/weddings.booking-timeline'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'
import { Route as QuoteAiRouteImport } from './routes/quote_.ai'
import { Route as HooksRecipeDripRouteImport } from './routes/hooks/recipe-drip'
import { Route as HooksNationalPricesMonthlyRouteImport } from './routes/hooks/national-prices-monthly'
import { Route as EventReferenceRouteImport } from './routes/event.$reference'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CateringQuoteRouteImport } from './routes/catering_.quote'
import { Route as BlogWinterWeddingCateringGuideRouteImport } from './routes/blog.winter-wedding-catering-guide'
import { Route as BlogSpringWeddingCateringGuideRouteImport } from './routes/blog.spring-wedding-catering-guide'
import { Route as BlogFallWeddingCateringGuideRouteImport } from './routes/blog.fall-wedding-catering-guide'
import { Route as ApiRecipeSignupRouteImport } from './routes/api/recipe-signup'
import { Route as ApiQuoteAssistantRouteImport } from './routes/api/quote-assistant'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUploadsRouteImport } from './routes/admin/uploads'
import { Route as AdminTrendsRouteImport } from './routes/admin/trends'
import { Route as AdminTimesheetRouteImport } from './routes/admin/timesheet'
import { Route as AdminSynonymsRouteImport } from './routes/admin/synonyms'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminSetPasswordRouteImport } from './routes/admin/set-password'
import { Route as AdminServingsReviewRouteImport } from './routes/admin/servings-review'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AdminScanFlyerRouteImport } from './routes/admin/scan-flyer'
import { Route as AdminScanAssetsRouteImport } from './routes/admin/scan-assets'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminRegisterRouteImport } from './routes/admin/register'
import { Route as AdminRecipesRouteImport } from './routes/admin/recipes'
import { Route as AdminRecipeHubRouteImport } from './routes/admin/recipe-hub'
import { Route as AdminReceiptsRouteImport } from './routes/admin/receipts'
import { Route as AdminQuotesRouteImport } from './routes/admin/quotes'
import { Route as AdminQuickQuoteRouteImport } from './routes/admin/quick-quote'
import { Route as AdminPurchaseOrdersRouteImport } from './routes/admin/purchase-orders'
import { Route as AdminNationalPricesRouteImport } from './routes/admin/national-prices'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminMarginVolatilityRouteImport } from './routes/admin/margin-volatility'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminIntelligenceRouteImport } from './routes/admin/intelligence'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminIngredientReferenceRouteImport } from './routes/admin/ingredient-reference'
import { Route as AdminImportRecipesRouteImport } from './routes/admin/import-recipes'
import { Route as AdminGenerateRecipePhotosRouteImport } from './routes/admin/generate-recipe-photos'
import { Route as AdminExportsRouteImport } from './routes/admin/exports'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminCompetitorsRouteImport } from './routes/admin/competitors'
import { Route as AdminCompetitorTrendsRouteImport } from './routes/admin/competitor-trends'
import { Route as AdminBrandColorsRouteImport } from './routes/admin/brand-colors'
import { Route as AdminAutoLinkIngredientsRouteImport } from './routes/admin/auto-link-ingredients'
import { Route as AdminAffiliatesRouteImport } from './routes/admin/affiliates'
import { Route as AdminAccessRouteImport } from './routes/admin/access'
import { Route as AdminCompetitorQuotesIndexRouteImport } from './routes/admin/competitor-quotes.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AdminSuppliersIdRouteImport } from './routes/admin/suppliers.$id'
import { Route as AdminSaleFlyersIdRouteImport } from './routes/admin/sale-flyers.$id'
import { Route as AdminRecipesNewRouteImport } from './routes/admin/recipes.new'
import { Route as AdminRecipeHubIdRouteImport } from './routes/admin/recipe-hub.$id'
import { Route as AdminQuotesIdRouteImport } from './routes/admin/quotes.$id'
import { Route as AdminPricingNationalRouteImport } from './routes/admin/pricing.national'
import { Route as AdminIngredientsReviewUnlinkedRouteImport } from './routes/admin/ingredients.review-unlinked'
import { Route as AdminCompetitorQuotesIdRouteImport } from './routes/admin/competitor-quotes.$id'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiRecipesIdPrintableRouteImport } from './routes/api/recipes.$id.printable'
import { Route as AdminRecipesIdEditRouteImport } from './routes/admin/recipes.$id.edit'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQuotesRoute = MyQuotesRouteImport.update({
  id: '/my-quotes',
  path: '/my-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowRoute = FollowRouteImport.update({
  id: '/follow',
  path: '/follow',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingsIndexRoute = WeddingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeddingsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WeddingsWinterClevelandOhioRoute =
  WeddingsWinterClevelandOhioRouteImport.update({
    id: '/winter-cleveland-ohio',
    path: '/winter-cleveland-ohio',
    getParentRoute: () => WeddingsRoute,
  } as any)
const WeddingsSpringAuroraOhioRoute =
  WeddingsSpringAuroraOhioRouteImport.update({
    id: '/spring-aurora-ohio',
    path: '/spring-aurora-ohio',
    getParentRoute: () => WeddingsRoute,
  } as any)
const WeddingsFallHudsonOhioRoute = WeddingsFallHudsonOhioRouteImport.update({
  id: '/fall-hudson-ohio',
  path: '/fall-hudson-ohio',
  getParentRoute: () => WeddingsRoute,
} as any)
const WeddingsBookingTimelineRoute = WeddingsBookingTimelineRouteImport.update({
  id: '/booking-timeline',
  path: '/booking-timeline',
  getParentRoute: () => WeddingsRoute,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecipesRoute,
} as any)
const QuoteAiRoute = QuoteAiRouteImport.update({
  id: '/quote_/ai',
  path: '/quote/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRecipeDripRoute = HooksRecipeDripRouteImport.update({
  id: '/hooks/recipe-drip',
  path: '/hooks/recipe-drip',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksNationalPricesMonthlyRoute =
  HooksNationalPricesMonthlyRouteImport.update({
    id: '/hooks/national-prices-monthly',
    path: '/hooks/national-prices-monthly',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventReferenceRoute = EventReferenceRouteImport.update({
  id: '/event/$reference',
  path: '/event/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringQuoteRoute = CateringQuoteRouteImport.update({
  id: '/catering_/quote',
  path: '/catering/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWinterWeddingCateringGuideRoute =
  BlogWinterWeddingCateringGuideRouteImport.update({
    id: '/blog/winter-wedding-catering-guide',
    path: '/blog/winter-wedding-catering-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSpringWeddingCateringGuideRoute =
  BlogSpringWeddingCateringGuideRouteImport.update({
    id: '/blog/spring-wedding-catering-guide',
    path: '/blog/spring-wedding-catering-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogFallWeddingCateringGuideRoute =
  BlogFallWeddingCateringGuideRouteImport.update({
    id: '/blog/fall-wedding-catering-guide',
    path: '/blog/fall-wedding-catering-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRecipeSignupRoute = ApiRecipeSignupRouteImport.update({
  id: '/api/recipe-signup',
  path: '/api/recipe-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteAssistantRoute = ApiQuoteAssistantRouteImport.update({
  id: '/api/quote-assistant',
  path: '/api/quote-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadsRoute = AdminUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrendsRoute = AdminTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimesheetRoute = AdminTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSynonymsRoute = AdminSynonymsRouteImport.update({
  id: '/synonyms',
  path: '/synonyms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetPasswordRoute = AdminSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServingsReviewRoute = AdminServingsReviewRouteImport.update({
  id: '/servings-review',
  path: '/servings-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScanFlyerRoute = AdminScanFlyerRouteImport.update({
  id: '/scan-flyer',
  path: '/scan-flyer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScanAssetsRoute = AdminScanAssetsRouteImport.update({
  id: '/scan-assets',
  path: '/scan-assets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesRoute = AdminRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipeHubRoute = AdminRecipeHubRouteImport.update({
  id: '/recipe-hub',
  path: '/recipe-hub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceiptsRoute = AdminReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuickQuoteRoute = AdminQuickQuoteRouteImport.update({
  id: '/quick-quote',
  path: '/quick-quote',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchaseOrdersRoute = AdminPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNationalPricesRoute = AdminNationalPricesRouteImport.update({
  id: '/national-prices',
  path: '/national-prices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarginVolatilityRoute = AdminMarginVolatilityRouteImport.update({
  id: '/margin-volatility',
  path: '/margin-volatility',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntelligenceRoute = AdminIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIngredientReferenceRoute =
  AdminIngredientReferenceRouteImport.update({
    id: '/ingredient-reference',
    path: '/ingredient-reference',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminImportRecipesRoute = AdminImportRecipesRouteImport.update({
  id: '/import-recipes',
  path: '/import-recipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenerateRecipePhotosRoute =
  AdminGenerateRecipePhotosRouteImport.update({
    id: '/generate-recipe-photos',
    path: '/generate-recipe-photos',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminExportsRoute = AdminExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitorsRoute = AdminCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitorTrendsRoute = AdminCompetitorTrendsRouteImport.update({
  id: '/competitor-trends',
  path: '/competitor-trends',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandColorsRoute = AdminBrandColorsRouteImport.update({
  id: '/brand-colors',
  path: '/brand-colors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutoLinkIngredientsRoute =
  AdminAutoLinkIngredientsRouteImport.update({
    id: '/auto-link-ingredients',
    path: '/auto-link-ingredients',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitorQuotesIndexRoute =
  AdminCompetitorQuotesIndexRouteImport.update({
    id: '/competitor-quotes/',
    path: '/competitor-quotes/',
    getParentRoute: () => AdminRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersIdRoute = AdminSuppliersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSuppliersRoute,
} as any)
const AdminSaleFlyersIdRoute = AdminSaleFlyersIdRouteImport.update({
  id: '/sale-flyers/$id',
  path: '/sale-flyers/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesNewRoute = AdminRecipesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRecipesRoute,
} as any)
const AdminRecipeHubIdRoute = AdminRecipeHubIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRecipeHubRoute,
} as any)
const AdminQuotesIdRoute = AdminQuotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminQuotesRoute,
} as any)
const AdminPricingNationalRoute = AdminPricingNationalRouteImport.update({
  id: '/pricing/national',
  path: '/pricing/national',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIngredientsReviewUnlinkedRoute =
  AdminIngredientsReviewUnlinkedRouteImport.update({
    id: '/ingredients/review-unlinked',
    path: '/ingredients/review-unlinked',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCompetitorQuotesIdRoute = AdminCompetitorQuotesIdRouteImport.update({
  id: '/competitor-quotes/$id',
  path: '/competitor-quotes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIdPrintableRoute = ApiRecipesIdPrintableRouteImport.update({
  id: '/api/recipes/$id/printable',
  path: '/api/recipes/$id/printable',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecipesIdEditRoute = AdminRecipesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminRecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employee': typeof EmployeeRoute
  '/follow': typeof FollowRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/menu': typeof MenuRoute
  '/my-events': typeof MyEventsRoute
  '/my-quotes': typeof MyQuotesRoute
  '/quote': typeof QuoteRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/auto-link-ingredients': typeof AdminAutoLinkIngredientsRoute
  '/admin/brand-colors': typeof AdminBrandColorsRoute
  '/admin/competitor-trends': typeof AdminCompetitorTrendsRoute
  '/admin/competitors': typeof AdminCompetitorsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/generate-recipe-photos': typeof AdminGenerateRecipePhotosRoute
  '/admin/import-recipes': typeof AdminImportRecipesRoute
  '/admin/ingredient-reference': typeof AdminIngredientReferenceRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/margin-volatility': typeof AdminMarginVolatilityRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/national-prices': typeof AdminNationalPricesRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/quick-quote': typeof AdminQuickQuoteRoute
  '/admin/quotes': typeof AdminQuotesRouteWithChildren
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/recipe-hub': typeof AdminRecipeHubRouteWithChildren
  '/admin/recipes': typeof AdminRecipesRouteWithChildren
  '/admin/register': typeof AdminRegisterRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/scan-assets': typeof AdminScanAssetsRoute
  '/admin/scan-flyer': typeof AdminScanFlyerRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/servings-review': typeof AdminServingsReviewRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/suppliers': typeof AdminSuppliersRouteWithChildren
  '/admin/synonyms': typeof AdminSynonymsRoute
  '/admin/timesheet': typeof AdminTimesheetRoute
  '/admin/trends': typeof AdminTrendsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/contact': typeof ApiContactRoute
  '/api/quote-assistant': typeof ApiQuoteAssistantRoute
  '/api/recipe-signup': typeof ApiRecipeSignupRoute
  '/blog/fall-wedding-catering-guide': typeof BlogFallWeddingCateringGuideRoute
  '/blog/spring-wedding-catering-guide': typeof BlogSpringWeddingCateringGuideRoute
  '/blog/winter-wedding-catering-guide': typeof BlogWinterWeddingCateringGuideRoute
  '/catering/quote': typeof CateringQuoteRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/event/$reference': typeof EventReferenceRoute
  '/hooks/national-prices-monthly': typeof HooksNationalPricesMonthlyRoute
  '/hooks/recipe-drip': typeof HooksRecipeDripRoute
  '/quote/ai': typeof QuoteAiRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/weddings/booking-timeline': typeof WeddingsBookingTimelineRoute
  '/weddings/fall-hudson-ohio': typeof WeddingsFallHudsonOhioRoute
  '/weddings/spring-aurora-ohio': typeof WeddingsSpringAuroraOhioRoute
  '/weddings/winter-cleveland-ohio': typeof WeddingsWinterClevelandOhioRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/weddings/': typeof WeddingsIndexRoute
  '/admin/competitor-quotes/$id': typeof AdminCompetitorQuotesIdRoute
  '/admin/ingredients/review-unlinked': typeof AdminIngredientsReviewUnlinkedRoute
  '/admin/pricing/national': typeof AdminPricingNationalRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/recipe-hub/$id': typeof AdminRecipeHubIdRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/admin/sale-flyers/$id': typeof AdminSaleFlyersIdRoute
  '/admin/suppliers/$id': typeof AdminSuppliersIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/competitor-quotes/': typeof AdminCompetitorQuotesIndexRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
  '/api/recipes/$id/printable': typeof ApiRecipesIdPrintableRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employee': typeof EmployeeRoute
  '/follow': typeof FollowRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/menu': typeof MenuRoute
  '/my-events': typeof MyEventsRoute
  '/my-quotes': typeof MyQuotesRoute
  '/quote': typeof QuoteRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/auto-link-ingredients': typeof AdminAutoLinkIngredientsRoute
  '/admin/brand-colors': typeof AdminBrandColorsRoute
  '/admin/competitor-trends': typeof AdminCompetitorTrendsRoute
  '/admin/competitors': typeof AdminCompetitorsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/generate-recipe-photos': typeof AdminGenerateRecipePhotosRoute
  '/admin/import-recipes': typeof AdminImportRecipesRoute
  '/admin/ingredient-reference': typeof AdminIngredientReferenceRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/margin-volatility': typeof AdminMarginVolatilityRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/national-prices': typeof AdminNationalPricesRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/quick-quote': typeof AdminQuickQuoteRoute
  '/admin/quotes': typeof AdminQuotesRouteWithChildren
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/recipe-hub': typeof AdminRecipeHubRouteWithChildren
  '/admin/recipes': typeof AdminRecipesRouteWithChildren
  '/admin/register': typeof AdminRegisterRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/scan-assets': typeof AdminScanAssetsRoute
  '/admin/scan-flyer': typeof AdminScanFlyerRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/servings-review': typeof AdminServingsReviewRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/suppliers': typeof AdminSuppliersRouteWithChildren
  '/admin/synonyms': typeof AdminSynonymsRoute
  '/admin/timesheet': typeof AdminTimesheetRoute
  '/admin/trends': typeof AdminTrendsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/contact': typeof ApiContactRoute
  '/api/quote-assistant': typeof ApiQuoteAssistantRoute
  '/api/recipe-signup': typeof ApiRecipeSignupRoute
  '/blog/fall-wedding-catering-guide': typeof BlogFallWeddingCateringGuideRoute
  '/blog/spring-wedding-catering-guide': typeof BlogSpringWeddingCateringGuideRoute
  '/blog/winter-wedding-catering-guide': typeof BlogWinterWeddingCateringGuideRoute
  '/catering/quote': typeof CateringQuoteRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/event/$reference': typeof EventReferenceRoute
  '/hooks/national-prices-monthly': typeof HooksNationalPricesMonthlyRoute
  '/hooks/recipe-drip': typeof HooksRecipeDripRoute
  '/quote/ai': typeof QuoteAiRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/weddings/booking-timeline': typeof WeddingsBookingTimelineRoute
  '/weddings/fall-hudson-ohio': typeof WeddingsFallHudsonOhioRoute
  '/weddings/spring-aurora-ohio': typeof WeddingsSpringAuroraOhioRoute
  '/weddings/winter-cleveland-ohio': typeof WeddingsWinterClevelandOhioRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/weddings': typeof WeddingsIndexRoute
  '/admin/competitor-quotes/$id': typeof AdminCompetitorQuotesIdRoute
  '/admin/ingredients/review-unlinked': typeof AdminIngredientsReviewUnlinkedRoute
  '/admin/pricing/national': typeof AdminPricingNationalRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/recipe-hub/$id': typeof AdminRecipeHubIdRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/admin/sale-flyers/$id': typeof AdminSaleFlyersIdRoute
  '/admin/suppliers/$id': typeof AdminSuppliersIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/competitor-quotes': typeof AdminCompetitorQuotesIndexRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
  '/api/recipes/$id/printable': typeof ApiRecipesIdPrintableRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employee': typeof EmployeeRoute
  '/follow': typeof FollowRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/menu': typeof MenuRoute
  '/my-events': typeof MyEventsRoute
  '/my-quotes': typeof MyQuotesRoute
  '/quote': typeof QuoteRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/auto-link-ingredients': typeof AdminAutoLinkIngredientsRoute
  '/admin/brand-colors': typeof AdminBrandColorsRoute
  '/admin/competitor-trends': typeof AdminCompetitorTrendsRoute
  '/admin/competitors': typeof AdminCompetitorsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/generate-recipe-photos': typeof AdminGenerateRecipePhotosRoute
  '/admin/import-recipes': typeof AdminImportRecipesRoute
  '/admin/ingredient-reference': typeof AdminIngredientReferenceRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/margin-volatility': typeof AdminMarginVolatilityRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/national-prices': typeof AdminNationalPricesRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/quick-quote': typeof AdminQuickQuoteRoute
  '/admin/quotes': typeof AdminQuotesRouteWithChildren
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/recipe-hub': typeof AdminRecipeHubRouteWithChildren
  '/admin/recipes': typeof AdminRecipesRouteWithChildren
  '/admin/register': typeof AdminRegisterRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/scan-assets': typeof AdminScanAssetsRoute
  '/admin/scan-flyer': typeof AdminScanFlyerRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/servings-review': typeof AdminServingsReviewRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/suppliers': typeof AdminSuppliersRouteWithChildren
  '/admin/synonyms': typeof AdminSynonymsRoute
  '/admin/timesheet': typeof AdminTimesheetRoute
  '/admin/trends': typeof AdminTrendsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/contact': typeof ApiContactRoute
  '/api/quote-assistant': typeof ApiQuoteAssistantRoute
  '/api/recipe-signup': typeof ApiRecipeSignupRoute
  '/blog/fall-wedding-catering-guide': typeof BlogFallWeddingCateringGuideRoute
  '/blog/spring-wedding-catering-guide': typeof BlogSpringWeddingCateringGuideRoute
  '/blog/winter-wedding-catering-guide': typeof BlogWinterWeddingCateringGuideRoute
  '/catering_/quote': typeof CateringQuoteRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/event/$reference': typeof EventReferenceRoute
  '/hooks/national-prices-monthly': typeof HooksNationalPricesMonthlyRoute
  '/hooks/recipe-drip': typeof HooksRecipeDripRoute
  '/quote_/ai': typeof QuoteAiRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/weddings/booking-timeline': typeof WeddingsBookingTimelineRoute
  '/weddings/fall-hudson-ohio': typeof WeddingsFallHudsonOhioRoute
  '/weddings/spring-aurora-ohio': typeof WeddingsSpringAuroraOhioRoute
  '/weddings/winter-cleveland-ohio': typeof WeddingsWinterClevelandOhioRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/weddings/': typeof WeddingsIndexRoute
  '/admin/competitor-quotes/$id': typeof AdminCompetitorQuotesIdRoute
  '/admin/ingredients/review-unlinked': typeof AdminIngredientsReviewUnlinkedRoute
  '/admin/pricing/national': typeof AdminPricingNationalRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/recipe-hub/$id': typeof AdminRecipeHubIdRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/admin/sale-flyers/$id': typeof AdminSaleFlyersIdRoute
  '/admin/suppliers/$id': typeof AdminSuppliersIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/competitor-quotes/': typeof AdminCompetitorQuotesIndexRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
  '/api/recipes/$id/printable': typeof ApiRecipesIdPrintableRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/catering'
    | '/contact'
    | '/dashboard'
    | '/employee'
    | '/follow'
    | '/forgot-password'
    | '/login'
    | '/lookup'
    | '/menu'
    | '/my-events'
    | '/my-quotes'
    | '/quote'
    | '/recipes'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/weddings'
    | '/admin/access'
    | '/admin/affiliates'
    | '/admin/auto-link-ingredients'
    | '/admin/brand-colors'
    | '/admin/competitor-trends'
    | '/admin/competitors'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/exports'
    | '/admin/generate-recipe-photos'
    | '/admin/import-recipes'
    | '/admin/ingredient-reference'
    | '/admin/integrations'
    | '/admin/intelligence'
    | '/admin/inventory'
    | '/admin/margin-volatility'
    | '/admin/menu'
    | '/admin/national-prices'
    | '/admin/purchase-orders'
    | '/admin/quick-quote'
    | '/admin/quotes'
    | '/admin/receipts'
    | '/admin/recipe-hub'
    | '/admin/recipes'
    | '/admin/register'
    | '/admin/sales'
    | '/admin/scan-assets'
    | '/admin/scan-flyer'
    | '/admin/schedule'
    | '/admin/servings-review'
    | '/admin/set-password'
    | '/admin/suppliers'
    | '/admin/synonyms'
    | '/admin/timesheet'
    | '/admin/trends'
    | '/admin/uploads'
    | '/admin/users'
    | '/api/contact'
    | '/api/quote-assistant'
    | '/api/recipe-signup'
    | '/blog/fall-wedding-catering-guide'
    | '/blog/spring-wedding-catering-guide'
    | '/blog/winter-wedding-catering-guide'
    | '/catering/quote'
    | '/email/unsubscribe'
    | '/event/$reference'
    | '/hooks/national-prices-monthly'
    | '/hooks/recipe-drip'
    | '/quote/ai'
    | '/recipes/$id'
    | '/weddings/booking-timeline'
    | '/weddings/fall-hudson-ohio'
    | '/weddings/spring-aurora-ohio'
    | '/weddings/winter-cleveland-ohio'
    | '/admin/'
    | '/blog/'
    | '/weddings/'
    | '/admin/competitor-quotes/$id'
    | '/admin/ingredients/review-unlinked'
    | '/admin/pricing/national'
    | '/admin/quotes/$id'
    | '/admin/recipe-hub/$id'
    | '/admin/recipes/new'
    | '/admin/sale-flyers/$id'
    | '/admin/suppliers/$id'
    | '/lovable/email/suppression'
    | '/admin/competitor-quotes/'
    | '/admin/recipes/$id/edit'
    | '/api/recipes/$id/printable'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catering'
    | '/contact'
    | '/dashboard'
    | '/employee'
    | '/follow'
    | '/forgot-password'
    | '/login'
    | '/lookup'
    | '/menu'
    | '/my-events'
    | '/my-quotes'
    | '/quote'
    | '/recipes'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/access'
    | '/admin/affiliates'
    | '/admin/auto-link-ingredients'
    | '/admin/brand-colors'
    | '/admin/competitor-trends'
    | '/admin/competitors'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/exports'
    | '/admin/generate-recipe-photos'
    | '/admin/import-recipes'
    | '/admin/ingredient-reference'
    | '/admin/integrations'
    | '/admin/intelligence'
    | '/admin/inventory'
    | '/admin/margin-volatility'
    | '/admin/menu'
    | '/admin/national-prices'
    | '/admin/purchase-orders'
    | '/admin/quick-quote'
    | '/admin/quotes'
    | '/admin/receipts'
    | '/admin/recipe-hub'
    | '/admin/recipes'
    | '/admin/register'
    | '/admin/sales'
    | '/admin/scan-assets'
    | '/admin/scan-flyer'
    | '/admin/schedule'
    | '/admin/servings-review'
    | '/admin/set-password'
    | '/admin/suppliers'
    | '/admin/synonyms'
    | '/admin/timesheet'
    | '/admin/trends'
    | '/admin/uploads'
    | '/admin/users'
    | '/api/contact'
    | '/api/quote-assistant'
    | '/api/recipe-signup'
    | '/blog/fall-wedding-catering-guide'
    | '/blog/spring-wedding-catering-guide'
    | '/blog/winter-wedding-catering-guide'
    | '/catering/quote'
    | '/email/unsubscribe'
    | '/event/$reference'
    | '/hooks/national-prices-monthly'
    | '/hooks/recipe-drip'
    | '/quote/ai'
    | '/recipes/$id'
    | '/weddings/booking-timeline'
    | '/weddings/fall-hudson-ohio'
    | '/weddings/spring-aurora-ohio'
    | '/weddings/winter-cleveland-ohio'
    | '/admin'
    | '/blog'
    | '/weddings'
    | '/admin/competitor-quotes/$id'
    | '/admin/ingredients/review-unlinked'
    | '/admin/pricing/national'
    | '/admin/quotes/$id'
    | '/admin/recipe-hub/$id'
    | '/admin/recipes/new'
    | '/admin/sale-flyers/$id'
    | '/admin/suppliers/$id'
    | '/lovable/email/suppression'
    | '/admin/competitor-quotes'
    | '/admin/recipes/$id/edit'
    | '/api/recipes/$id/printable'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/catering'
    | '/contact'
    | '/dashboard'
    | '/employee'
    | '/follow'
    | '/forgot-password'
    | '/login'
    | '/lookup'
    | '/menu'
    | '/my-events'
    | '/my-quotes'
    | '/quote'
    | '/recipes'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/weddings'
    | '/admin/access'
    | '/admin/affiliates'
    | '/admin/auto-link-ingredients'
    | '/admin/brand-colors'
    | '/admin/competitor-trends'
    | '/admin/competitors'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/exports'
    | '/admin/generate-recipe-photos'
    | '/admin/import-recipes'
    | '/admin/ingredient-reference'
    | '/admin/integrations'
    | '/admin/intelligence'
    | '/admin/inventory'
    | '/admin/margin-volatility'
    | '/admin/menu'
    | '/admin/national-prices'
    | '/admin/purchase-orders'
    | '/admin/quick-quote'
    | '/admin/quotes'
    | '/admin/receipts'
    | '/admin/recipe-hub'
    | '/admin/recipes'
    | '/admin/register'
    | '/admin/sales'
    | '/admin/scan-assets'
    | '/admin/scan-flyer'
    | '/admin/schedule'
    | '/admin/servings-review'
    | '/admin/set-password'
    | '/admin/suppliers'
    | '/admin/synonyms'
    | '/admin/timesheet'
    | '/admin/trends'
    | '/admin/uploads'
    | '/admin/users'
    | '/api/contact'
    | '/api/quote-assistant'
    | '/api/recipe-signup'
    | '/blog/fall-wedding-catering-guide'
    | '/blog/spring-wedding-catering-guide'
    | '/blog/winter-wedding-catering-guide'
    | '/catering_/quote'
    | '/email/unsubscribe'
    | '/event/$reference'
    | '/hooks/national-prices-monthly'
    | '/hooks/recipe-drip'
    | '/quote_/ai'
    | '/recipes/$id'
    | '/weddings/booking-timeline'
    | '/weddings/fall-hudson-ohio'
    | '/weddings/spring-aurora-ohio'
    | '/weddings/winter-cleveland-ohio'
    | '/admin/'
    | '/blog/'
    | '/weddings/'
    | '/admin/competitor-quotes/$id'
    | '/admin/ingredients/review-unlinked'
    | '/admin/pricing/national'
    | '/admin/quotes/$id'
    | '/admin/recipe-hub/$id'
    | '/admin/recipes/new'
    | '/admin/sale-flyers/$id'
    | '/admin/suppliers/$id'
    | '/lovable/email/suppression'
    | '/admin/competitor-quotes/'
    | '/admin/recipes/$id/edit'
    | '/api/recipes/$id/printable'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CateringRoute: typeof CateringRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EmployeeRoute: typeof EmployeeRoute
  FollowRoute: typeof FollowRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LookupRoute: typeof LookupRoute
  MenuRoute: typeof MenuRoute
  MyEventsRoute: typeof MyEventsRoute
  MyQuotesRoute: typeof MyQuotesRoute
  QuoteRoute: typeof QuoteRoute
  RecipesRoute: typeof RecipesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingsRoute: typeof WeddingsRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  ApiQuoteAssistantRoute: typeof ApiQuoteAssistantRoute
  ApiRecipeSignupRoute: typeof ApiRecipeSignupRoute
  BlogFallWeddingCateringGuideRoute: typeof BlogFallWeddingCateringGuideRoute
  BlogSpringWeddingCateringGuideRoute: typeof BlogSpringWeddingCateringGuideRoute
  BlogWinterWeddingCateringGuideRoute: typeof BlogWinterWeddingCateringGuideRoute
  CateringQuoteRoute: typeof CateringQuoteRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EventReferenceRoute: typeof EventReferenceRoute
  HooksNationalPricesMonthlyRoute: typeof HooksNationalPricesMonthlyRoute
  HooksRecipeDripRoute: typeof HooksRecipeDripRoute
  QuoteAiRoute: typeof QuoteAiRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiRecipesIdPrintableRoute: typeof ApiRecipesIdPrintableRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-quotes': {
      id: '/my-quotes'
      path: '/my-quotes'
      fullPath: '/my-quotes'
      preLoaderRoute: typeof MyQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow': {
      id: '/follow'
      path: '/follow'
      fullPath: '/follow'
      preLoaderRoute: typeof FollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weddings/': {
      id: '/weddings/'
      path: '/'
      fullPath: '/weddings/'
      preLoaderRoute: typeof WeddingsIndexRouteImport
      parentRoute: typeof WeddingsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/weddings/winter-cleveland-ohio': {
      id: '/weddings/winter-cleveland-ohio'
      path: '/winter-cleveland-ohio'
      fullPath: '/weddings/winter-cleveland-ohio'
      preLoaderRoute: typeof WeddingsWinterClevelandOhioRouteImport
      parentRoute: typeof WeddingsRoute
    }
    '/weddings/spring-aurora-ohio': {
      id: '/weddings/spring-aurora-ohio'
      path: '/spring-aurora-ohio'
      fullPath: '/weddings/spring-aurora-ohio'
      preLoaderRoute: typeof WeddingsSpringAuroraOhioRouteImport
      parentRoute: typeof WeddingsRoute
    }
    '/weddings/fall-hudson-ohio': {
      id: '/weddings/fall-hudson-ohio'
      path: '/fall-hudson-ohio'
      fullPath: '/weddings/fall-hudson-ohio'
      preLoaderRoute: typeof WeddingsFallHudsonOhioRouteImport
      parentRoute: typeof WeddingsRoute
    }
    '/weddings/booking-timeline': {
      id: '/weddings/booking-timeline'
      path: '/booking-timeline'
      fullPath: '/weddings/booking-timeline'
      preLoaderRoute: typeof WeddingsBookingTimelineRouteImport
      parentRoute: typeof WeddingsRoute
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/quote_/ai': {
      id: '/quote_/ai'
      path: '/quote/ai'
      fullPath: '/quote/ai'
      preLoaderRoute: typeof QuoteAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/recipe-drip': {
      id: '/hooks/recipe-drip'
      path: '/hooks/recipe-drip'
      fullPath: '/hooks/recipe-drip'
      preLoaderRoute: typeof HooksRecipeDripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/national-prices-monthly': {
      id: '/hooks/national-prices-monthly'
      path: '/hooks/national-prices-monthly'
      fullPath: '/hooks/national-prices-monthly'
      preLoaderRoute: typeof HooksNationalPricesMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$reference': {
      id: '/event/$reference'
      path: '/event/$reference'
      fullPath: '/event/$reference'
      preLoaderRoute: typeof EventReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering_/quote': {
      id: '/catering_/quote'
      path: '/catering/quote'
      fullPath: '/catering/quote'
      preLoaderRoute: typeof CateringQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/winter-wedding-catering-guide': {
      id: '/blog/winter-wedding-catering-guide'
      path: '/blog/winter-wedding-catering-guide'
      fullPath: '/blog/winter-wedding-catering-guide'
      preLoaderRoute: typeof BlogWinterWeddingCateringGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/spring-wedding-catering-guide': {
      id: '/blog/spring-wedding-catering-guide'
      path: '/blog/spring-wedding-catering-guide'
      fullPath: '/blog/spring-wedding-catering-guide'
      preLoaderRoute: typeof BlogSpringWeddingCateringGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/fall-wedding-catering-guide': {
      id: '/blog/fall-wedding-catering-guide'
      path: '/blog/fall-wedding-catering-guide'
      fullPath: '/blog/fall-wedding-catering-guide'
      preLoaderRoute: typeof BlogFallWeddingCateringGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipe-signup': {
      id: '/api/recipe-signup'
      path: '/api/recipe-signup'
      fullPath: '/api/recipe-signup'
      preLoaderRoute: typeof ApiRecipeSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote-assistant': {
      id: '/api/quote-assistant'
      path: '/api/quote-assistant'
      fullPath: '/api/quote-assistant'
      preLoaderRoute: typeof ApiQuoteAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/uploads': {
      id: '/admin/uploads'
      path: '/uploads'
      fullPath: '/admin/uploads'
      preLoaderRoute: typeof AdminUploadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trends': {
      id: '/admin/trends'
      path: '/trends'
      fullPath: '/admin/trends'
      preLoaderRoute: typeof AdminTrendsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timesheet': {
      id: '/admin/timesheet'
      path: '/timesheet'
      fullPath: '/admin/timesheet'
      preLoaderRoute: typeof AdminTimesheetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/synonyms': {
      id: '/admin/synonyms'
      path: '/synonyms'
      fullPath: '/admin/synonyms'
      preLoaderRoute: typeof AdminSynonymsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/set-password': {
      id: '/admin/set-password'
      path: '/set-password'
      fullPath: '/admin/set-password'
      preLoaderRoute: typeof AdminSetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servings-review': {
      id: '/admin/servings-review'
      path: '/servings-review'
      fullPath: '/admin/servings-review'
      preLoaderRoute: typeof AdminServingsReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scan-flyer': {
      id: '/admin/scan-flyer'
      path: '/scan-flyer'
      fullPath: '/admin/scan-flyer'
      preLoaderRoute: typeof AdminScanFlyerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scan-assets': {
      id: '/admin/scan-assets'
      path: '/scan-assets'
      fullPath: '/admin/scan-assets'
      preLoaderRoute: typeof AdminScanAssetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes': {
      id: '/admin/recipes'
      path: '/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AdminRecipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipe-hub': {
      id: '/admin/recipe-hub'
      path: '/recipe-hub'
      fullPath: '/admin/recipe-hub'
      preLoaderRoute: typeof AdminRecipeHubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receipts': {
      id: '/admin/receipts'
      path: '/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AdminReceiptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quick-quote': {
      id: '/admin/quick-quote'
      path: '/quick-quote'
      fullPath: '/admin/quick-quote'
      preLoaderRoute: typeof AdminQuickQuoteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchase-orders': {
      id: '/admin/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AdminPurchaseOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/national-prices': {
      id: '/admin/national-prices'
      path: '/national-prices'
      fullPath: '/admin/national-prices'
      preLoaderRoute: typeof AdminNationalPricesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/margin-volatility': {
      id: '/admin/margin-volatility'
      path: '/margin-volatility'
      fullPath: '/admin/margin-volatility'
      preLoaderRoute: typeof AdminMarginVolatilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intelligence': {
      id: '/admin/intelligence'
      path: '/intelligence'
      fullPath: '/admin/intelligence'
      preLoaderRoute: typeof AdminIntelligenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ingredient-reference': {
      id: '/admin/ingredient-reference'
      path: '/ingredient-reference'
      fullPath: '/admin/ingredient-reference'
      preLoaderRoute: typeof AdminIngredientReferenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import-recipes': {
      id: '/admin/import-recipes'
      path: '/import-recipes'
      fullPath: '/admin/import-recipes'
      preLoaderRoute: typeof AdminImportRecipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generate-recipe-photos': {
      id: '/admin/generate-recipe-photos'
      path: '/generate-recipe-photos'
      fullPath: '/admin/generate-recipe-photos'
      preLoaderRoute: typeof AdminGenerateRecipePhotosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exports': {
      id: '/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminExportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitors': {
      id: '/admin/competitors'
      path: '/competitors'
      fullPath: '/admin/competitors'
      preLoaderRoute: typeof AdminCompetitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitor-trends': {
      id: '/admin/competitor-trends'
      path: '/competitor-trends'
      fullPath: '/admin/competitor-trends'
      preLoaderRoute: typeof AdminCompetitorTrendsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brand-colors': {
      id: '/admin/brand-colors'
      path: '/brand-colors'
      fullPath: '/admin/brand-colors'
      preLoaderRoute: typeof AdminBrandColorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auto-link-ingredients': {
      id: '/admin/auto-link-ingredients'
      path: '/auto-link-ingredients'
      fullPath: '/admin/auto-link-ingredients'
      preLoaderRoute: typeof AdminAutoLinkIngredientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitor-quotes/': {
      id: '/admin/competitor-quotes/'
      path: '/competitor-quotes'
      fullPath: '/admin/competitor-quotes/'
      preLoaderRoute: typeof AdminCompetitorQuotesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers/$id': {
      id: '/admin/suppliers/$id'
      path: '/$id'
      fullPath: '/admin/suppliers/$id'
      preLoaderRoute: typeof AdminSuppliersIdRouteImport
      parentRoute: typeof AdminSuppliersRoute
    }
    '/admin/sale-flyers/$id': {
      id: '/admin/sale-flyers/$id'
      path: '/sale-flyers/$id'
      fullPath: '/admin/sale-flyers/$id'
      preLoaderRoute: typeof AdminSaleFlyersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/new': {
      id: '/admin/recipes/new'
      path: '/new'
      fullPath: '/admin/recipes/new'
      preLoaderRoute: typeof AdminRecipesNewRouteImport
      parentRoute: typeof AdminRecipesRoute
    }
    '/admin/recipe-hub/$id': {
      id: '/admin/recipe-hub/$id'
      path: '/$id'
      fullPath: '/admin/recipe-hub/$id'
      preLoaderRoute: typeof AdminRecipeHubIdRouteImport
      parentRoute: typeof AdminRecipeHubRoute
    }
    '/admin/quotes/$id': {
      id: '/admin/quotes/$id'
      path: '/$id'
      fullPath: '/admin/quotes/$id'
      preLoaderRoute: typeof AdminQuotesIdRouteImport
      parentRoute: typeof AdminQuotesRoute
    }
    '/admin/pricing/national': {
      id: '/admin/pricing/national'
      path: '/pricing/national'
      fullPath: '/admin/pricing/national'
      preLoaderRoute: typeof AdminPricingNationalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ingredients/review-unlinked': {
      id: '/admin/ingredients/review-unlinked'
      path: '/ingredients/review-unlinked'
      fullPath: '/admin/ingredients/review-unlinked'
      preLoaderRoute: typeof AdminIngredientsReviewUnlinkedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitor-quotes/$id': {
      id: '/admin/competitor-quotes/$id'
      path: '/competitor-quotes/$id'
      fullPath: '/admin/competitor-quotes/$id'
      preLoaderRoute: typeof AdminCompetitorQuotesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/$id/printable': {
      id: '/api/recipes/$id/printable'
      path: '/api/recipes/$id/printable'
      fullPath: '/api/recipes/$id/printable'
      preLoaderRoute: typeof ApiRecipesIdPrintableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recipes/$id/edit': {
      id: '/admin/recipes/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/recipes/$id/edit'
      preLoaderRoute: typeof AdminRecipesIdEditRouteImport
      parentRoute: typeof AdminRecipesRoute
    }
  }
}

interface AdminQuotesRouteChildren {
  AdminQuotesIdRoute: typeof AdminQuotesIdRoute
}

const AdminQuotesRouteChildren: AdminQuotesRouteChildren = {
  AdminQuotesIdRoute: AdminQuotesIdRoute,
}

const AdminQuotesRouteWithChildren = AdminQuotesRoute._addFileChildren(
  AdminQuotesRouteChildren,
)

interface AdminRecipeHubRouteChildren {
  AdminRecipeHubIdRoute: typeof AdminRecipeHubIdRoute
}

const AdminRecipeHubRouteChildren: AdminRecipeHubRouteChildren = {
  AdminRecipeHubIdRoute: AdminRecipeHubIdRoute,
}

const AdminRecipeHubRouteWithChildren = AdminRecipeHubRoute._addFileChildren(
  AdminRecipeHubRouteChildren,
)

interface AdminRecipesRouteChildren {
  AdminRecipesNewRoute: typeof AdminRecipesNewRoute
  AdminRecipesIdEditRoute: typeof AdminRecipesIdEditRoute
}

const AdminRecipesRouteChildren: AdminRecipesRouteChildren = {
  AdminRecipesNewRoute: AdminRecipesNewRoute,
  AdminRecipesIdEditRoute: AdminRecipesIdEditRoute,
}

const AdminRecipesRouteWithChildren = AdminRecipesRoute._addFileChildren(
  AdminRecipesRouteChildren,
)

interface AdminSuppliersRouteChildren {
  AdminSuppliersIdRoute: typeof AdminSuppliersIdRoute
}

const AdminSuppliersRouteChildren: AdminSuppliersRouteChildren = {
  AdminSuppliersIdRoute: AdminSuppliersIdRoute,
}

const AdminSuppliersRouteWithChildren = AdminSuppliersRoute._addFileChildren(
  AdminSuppliersRouteChildren,
)

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminAutoLinkIngredientsRoute: typeof AdminAutoLinkIngredientsRoute
  AdminBrandColorsRoute: typeof AdminBrandColorsRoute
  AdminCompetitorTrendsRoute: typeof AdminCompetitorTrendsRoute
  AdminCompetitorsRoute: typeof AdminCompetitorsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminExportsRoute: typeof AdminExportsRoute
  AdminGenerateRecipePhotosRoute: typeof AdminGenerateRecipePhotosRoute
  AdminImportRecipesRoute: typeof AdminImportRecipesRoute
  AdminIngredientReferenceRoute: typeof AdminIngredientReferenceRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminIntelligenceRoute: typeof AdminIntelligenceRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMarginVolatilityRoute: typeof AdminMarginVolatilityRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminNationalPricesRoute: typeof AdminNationalPricesRoute
  AdminPurchaseOrdersRoute: typeof AdminPurchaseOrdersRoute
  AdminQuickQuoteRoute: typeof AdminQuickQuoteRoute
  AdminQuotesRoute: typeof AdminQuotesRouteWithChildren
  AdminReceiptsRoute: typeof AdminReceiptsRoute
  AdminRecipeHubRoute: typeof AdminRecipeHubRouteWithChildren
  AdminRecipesRoute: typeof AdminRecipesRouteWithChildren
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminScanAssetsRoute: typeof AdminScanAssetsRoute
  AdminScanFlyerRoute: typeof AdminScanFlyerRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminServingsReviewRoute: typeof AdminServingsReviewRoute
  AdminSetPasswordRoute: typeof AdminSetPasswordRoute
  AdminSuppliersRoute: typeof AdminSuppliersRouteWithChildren
  AdminSynonymsRoute: typeof AdminSynonymsRoute
  AdminTimesheetRoute: typeof AdminTimesheetRoute
  AdminTrendsRoute: typeof AdminTrendsRoute
  AdminUploadsRoute: typeof AdminUploadsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCompetitorQuotesIdRoute: typeof AdminCompetitorQuotesIdRoute
  AdminIngredientsReviewUnlinkedRoute: typeof AdminIngredientsReviewUnlinkedRoute
  AdminPricingNationalRoute: typeof AdminPricingNationalRoute
  AdminSaleFlyersIdRoute: typeof AdminSaleFlyersIdRoute
  AdminCompetitorQuotesIndexRoute: typeof AdminCompetitorQuotesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminAutoLinkIngredientsRoute: AdminAutoLinkIngredientsRoute,
  AdminBrandColorsRoute: AdminBrandColorsRoute,
  AdminCompetitorTrendsRoute: AdminCompetitorTrendsRoute,
  AdminCompetitorsRoute: AdminCompetitorsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminExportsRoute: AdminExportsRoute,
  AdminGenerateRecipePhotosRoute: AdminGenerateRecipePhotosRoute,
  AdminImportRecipesRoute: AdminImportRecipesRoute,
  AdminIngredientReferenceRoute: AdminIngredientReferenceRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminIntelligenceRoute: AdminIntelligenceRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMarginVolatilityRoute: AdminMarginVolatilityRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminNationalPricesRoute: AdminNationalPricesRoute,
  AdminPurchaseOrdersRoute: AdminPurchaseOrdersRoute,
  AdminQuickQuoteRoute: AdminQuickQuoteRoute,
  AdminQuotesRoute: AdminQuotesRouteWithChildren,
  AdminReceiptsRoute: AdminReceiptsRoute,
  AdminRecipeHubRoute: AdminRecipeHubRouteWithChildren,
  AdminRecipesRoute: AdminRecipesRouteWithChildren,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminScanAssetsRoute: AdminScanAssetsRoute,
  AdminScanFlyerRoute: AdminScanFlyerRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminServingsReviewRoute: AdminServingsReviewRoute,
  AdminSetPasswordRoute: AdminSetPasswordRoute,
  AdminSuppliersRoute: AdminSuppliersRouteWithChildren,
  AdminSynonymsRoute: AdminSynonymsRoute,
  AdminTimesheetRoute: AdminTimesheetRoute,
  AdminTrendsRoute: AdminTrendsRoute,
  AdminUploadsRoute: AdminUploadsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCompetitorQuotesIdRoute: AdminCompetitorQuotesIdRoute,
  AdminIngredientsReviewUnlinkedRoute: AdminIngredientsReviewUnlinkedRoute,
  AdminPricingNationalRoute: AdminPricingNationalRoute,
  AdminSaleFlyersIdRoute: AdminSaleFlyersIdRoute,
  AdminCompetitorQuotesIndexRoute: AdminCompetitorQuotesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RecipesRouteChildren {
  RecipesIdRoute: typeof RecipesIdRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesIdRoute: RecipesIdRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

interface WeddingsRouteChildren {
  WeddingsBookingTimelineRoute: typeof WeddingsBookingTimelineRoute
  WeddingsFallHudsonOhioRoute: typeof WeddingsFallHudsonOhioRoute
  WeddingsSpringAuroraOhioRoute: typeof WeddingsSpringAuroraOhioRoute
  WeddingsWinterClevelandOhioRoute: typeof WeddingsWinterClevelandOhioRoute
  WeddingsIndexRoute: typeof WeddingsIndexRoute
}

const WeddingsRouteChildren: WeddingsRouteChildren = {
  WeddingsBookingTimelineRoute: WeddingsBookingTimelineRoute,
  WeddingsFallHudsonOhioRoute: WeddingsFallHudsonOhioRoute,
  WeddingsSpringAuroraOhioRoute: WeddingsSpringAuroraOhioRoute,
  WeddingsWinterClevelandOhioRoute: WeddingsWinterClevelandOhioRoute,
  WeddingsIndexRoute: WeddingsIndexRoute,
}

const WeddingsRouteWithChildren = WeddingsRoute._addFileChildren(
  WeddingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CateringRoute: CateringRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EmployeeRoute: EmployeeRoute,
  FollowRoute: FollowRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LookupRoute: LookupRoute,
  MenuRoute: MenuRoute,
  MyEventsRoute: MyEventsRoute,
  MyQuotesRoute: MyQuotesRoute,
  QuoteRoute: QuoteRoute,
  RecipesRoute: RecipesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingsRoute: WeddingsRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  ApiQuoteAssistantRoute: ApiQuoteAssistantRoute,
  ApiRecipeSignupRoute: ApiRecipeSignupRoute,
  BlogFallWeddingCateringGuideRoute: BlogFallWeddingCateringGuideRoute,
  BlogSpringWeddingCateringGuideRoute: BlogSpringWeddingCateringGuideRoute,
  BlogWinterWeddingCateringGuideRoute: BlogWinterWeddingCateringGuideRoute,
  CateringQuoteRoute: CateringQuoteRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EventReferenceRoute: EventReferenceRoute,
  HooksNationalPricesMonthlyRoute: HooksNationalPricesMonthlyRoute,
  HooksRecipeDripRoute: HooksRecipeDripRoute,
  QuoteAiRoute: QuoteAiRoute,
  BlogIndexRoute: BlogIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiRecipesIdPrintableRoute: ApiRecipesIdPrintableRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
