/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as MyQuotesRouteImport } from './routes/my-quotes'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EventReferenceRouteImport } from './routes/event.$reference'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminSetPasswordRouteImport } from './routes/admin/set-password'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AdminRegisterRouteImport } from './routes/admin/register'
import { Route as AdminRecipesRouteImport } from './routes/admin/recipes'
import { Route as AdminReceiptsRouteImport } from './routes/admin/receipts'
import { Route as AdminQuotesRouteImport } from './routes/admin/quotes'
import { Route as AdminPurchaseOrdersRouteImport } from './routes/admin/purchase-orders'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQuotesRoute = MyQuotesRouteImport.update({
  id: '/my-quotes',
  path: '/my-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EventReferenceRoute = EventReferenceRouteImport.update({
  id: '/event/$reference',
  path: '/event/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetPasswordRoute = AdminSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesRoute = AdminRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceiptsRoute = AdminReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchaseOrdersRoute = AdminPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/my-events': typeof MyEventsRoute
  '/my-quotes': typeof MyQuotesRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/event/$reference': typeof EventReferenceRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/my-events': typeof MyEventsRoute
  '/my-quotes': typeof MyQuotesRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/event/$reference': typeof EventReferenceRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/my-events': typeof MyEventsRoute
  '/my-quotes': typeof MyQuotesRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/event/$reference': typeof EventReferenceRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/lookup'
    | '/my-events'
    | '/my-quotes'
    | '/quote'
    | '/reset-password'
    | '/signup'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/inventory'
    | '/admin/purchase-orders'
    | '/admin/quotes'
    | '/admin/receipts'
    | '/admin/recipes'
    | '/admin/register'
    | '/admin/schedule'
    | '/admin/set-password'
    | '/admin/suppliers'
    | '/admin/users'
    | '/event/$reference'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/lookup'
    | '/my-events'
    | '/my-quotes'
    | '/quote'
    | '/reset-password'
    | '/signup'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/inventory'
    | '/admin/purchase-orders'
    | '/admin/quotes'
    | '/admin/receipts'
    | '/admin/recipes'
    | '/admin/register'
    | '/admin/schedule'
    | '/admin/set-password'
    | '/admin/suppliers'
    | '/admin/users'
    | '/event/$reference'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/lookup'
    | '/my-events'
    | '/my-quotes'
    | '/quote'
    | '/reset-password'
    | '/signup'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/inventory'
    | '/admin/purchase-orders'
    | '/admin/quotes'
    | '/admin/receipts'
    | '/admin/recipes'
    | '/admin/register'
    | '/admin/schedule'
    | '/admin/set-password'
    | '/admin/suppliers'
    | '/admin/users'
    | '/event/$reference'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LookupRoute: typeof LookupRoute
  MyEventsRoute: typeof MyEventsRoute
  MyQuotesRoute: typeof MyQuotesRoute
  QuoteRoute: typeof QuoteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  EventReferenceRoute: typeof EventReferenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-quotes': {
      id: '/my-quotes'
      path: '/my-quotes'
      fullPath: '/my-quotes'
      preLoaderRoute: typeof MyQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/event/$reference': {
      id: '/event/$reference'
      path: '/event/$reference'
      fullPath: '/event/$reference'
      preLoaderRoute: typeof EventReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/set-password': {
      id: '/admin/set-password'
      path: '/set-password'
      fullPath: '/admin/set-password'
      preLoaderRoute: typeof AdminSetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes': {
      id: '/admin/recipes'
      path: '/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AdminRecipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receipts': {
      id: '/admin/receipts'
      path: '/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AdminReceiptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchase-orders': {
      id: '/admin/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AdminPurchaseOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminPurchaseOrdersRoute: typeof AdminPurchaseOrdersRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminReceiptsRoute: typeof AdminReceiptsRoute
  AdminRecipesRoute: typeof AdminRecipesRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSetPasswordRoute: typeof AdminSetPasswordRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminPurchaseOrdersRoute: AdminPurchaseOrdersRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminReceiptsRoute: AdminReceiptsRoute,
  AdminRecipesRoute: AdminRecipesRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSetPasswordRoute: AdminSetPasswordRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LookupRoute: LookupRoute,
  MyEventsRoute: MyEventsRoute,
  MyQuotesRoute: MyQuotesRoute,
  QuoteRoute: QuoteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  EventReferenceRoute: EventReferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
