/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as MyQuotesRouteImport } from './routes/my-quotes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminRegisterRouteImport } from './routes/admin/register'
import { Route as AdminRecipesRouteImport } from './routes/admin/recipes'
import { Route as AdminReceiptsRouteImport } from './routes/admin/receipts'
import { Route as AdminQuotesRouteImport } from './routes/admin/quotes'
import { Route as AdminPurchaseOrdersRouteImport } from './routes/admin/purchase-orders'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQuotesRoute = MyQuotesRouteImport.update({
  id: '/my-quotes',
  path: '/my-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesRoute = AdminRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceiptsRoute = AdminReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchaseOrdersRoute = AdminPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/my-quotes': typeof MyQuotesRoute
  '/quote': typeof QuoteRoute
  '/signup': typeof SignupRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-quotes': typeof MyQuotesRoute
  '/quote': typeof QuoteRoute
  '/signup': typeof SignupRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/my-quotes': typeof MyQuotesRoute
  '/quote': typeof QuoteRoute
  '/signup': typeof SignupRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/my-quotes'
    | '/quote'
    | '/signup'
    | '/admin/inventory'
    | '/admin/purchase-orders'
    | '/admin/quotes'
    | '/admin/receipts'
    | '/admin/recipes'
    | '/admin/register'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my-quotes'
    | '/quote'
    | '/signup'
    | '/admin/inventory'
    | '/admin/purchase-orders'
    | '/admin/quotes'
    | '/admin/receipts'
    | '/admin/recipes'
    | '/admin/register'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/my-quotes'
    | '/quote'
    | '/signup'
    | '/admin/inventory'
    | '/admin/purchase-orders'
    | '/admin/quotes'
    | '/admin/receipts'
    | '/admin/recipes'
    | '/admin/register'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyQuotesRoute: typeof MyQuotesRoute
  QuoteRoute: typeof QuoteRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-quotes': {
      id: '/my-quotes'
      path: '/my-quotes'
      fullPath: '/my-quotes'
      preLoaderRoute: typeof MyQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes': {
      id: '/admin/recipes'
      path: '/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AdminRecipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receipts': {
      id: '/admin/receipts'
      path: '/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AdminReceiptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchase-orders': {
      id: '/admin/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AdminPurchaseOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminPurchaseOrdersRoute: typeof AdminPurchaseOrdersRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminReceiptsRoute: typeof AdminReceiptsRoute
  AdminRecipesRoute: typeof AdminRecipesRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventoryRoute: AdminInventoryRoute,
  AdminPurchaseOrdersRoute: AdminPurchaseOrdersRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminReceiptsRoute: AdminReceiptsRoute,
  AdminRecipesRoute: AdminRecipesRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MyQuotesRoute: MyQuotesRoute,
  QuoteRoute: QuoteRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
