INSERT INTO public.feature_visibility (feature_key, phase, nav_enabled) VALUES
  ('admin_quotes','public',true),
  ('admin_quote_lab','public',true),
  ('admin_quote_ai_review','public',true),
  ('admin_recipe_hub','public',true),
  ('admin_menu_control','public',true),
  ('admin_menu_modules','public',true),
  ('admin_inspired_preview','public',true),
  ('admin_cooking_guides','public',true),
  ('admin_newsletter_guide','public',true),
  ('admin_events','public',true),
  ('admin_schedule','public',true),
  ('admin_employees','public',true),
  ('admin_timesheets','public',true),
  ('admin_inventory','public',true),
  ('admin_purchase_orders','public',true),
  ('admin_competitors','public',true),
  ('admin_competitor_quotes','public',true),
  ('admin_competitor_trends','public',true),
  ('admin_sales_flyers','public',true),
  ('admin_feature_visibility','public',true),
  ('admin_page_inventory','public',true),
  ('admin_audit_log','public',true),
  ('admin_change_log','public',true),
  ('admin_project_intelligence','public',true),
  ('admin_access_control','public',true),
  ('admin_integrations','public',true),
  ('admin_brand_management','public',true)
ON CONFLICT (feature_key) DO UPDATE
  SET phase = 'public',
      nav_enabled = true,
      updated_at = now();