/**
 * Pricing Code Inventory — read-only catalogue of every file in the repo
 * that touches pricing, costing, units, conversions, inventory valuation,
 * or quote pricing. Generated by manual repo audit.
 *
 * NOTHING in this file mutates application state. It exists purely so
 * admins can review and export the inventory as PDF or JSON.
 */

export type PricingLayer =
  | "Baseline cost ingestion"
  | "Cost normalization"
  | "Unit conversion"
  | "Recipe cost calculation"
  | "Pricing model"
  | "Quote application"
  | "Guardrails / validation";

export type Recommendation = "KEEP" | "CENTRALIZE" | "EXPOSE" | "LEGACY";

export type PricingFileEntry = {
  path: string;
  does: string;
  layers: PricingLayer[];
  notes?: string;
  recommendation: Recommendation;
};

export type PricingInventorySection = {
  title: string;
  description?: string;
  entries: PricingFileEntry[];
};

export const PRICING_INVENTORY_GENERATED_AT = "2026-04-25";

export const PRICING_INVENTORY: PricingInventorySection[] = [
  {
    title: "1. Cost normalization & unit conversion (foundation)",
    entries: [
      {
        path: "src/lib/recipe-costing.ts",
        does: "Pure utility. Defines WEIGHT_TO_LB, VOLUME_TO_QT, VOLUME_TO_LITER lookup tables. Exports convertQty(qty, fromUnit, toUnit), getConvertedUnitCost(...), getIngredientCostMetrics({...}). Used by recipe cost recompute, national-floor re-pricing, and quote re-pricing.",
        layers: ["Cost normalization", "Unit conversion"],
        notes: "Imperial + metric weight/volume only. No density bridging weight↔volume. No each/count conversions. Hard-coded constants. Imported by apply-national-floor.functions.ts.",
        recommendation: "CENTRALIZE",
      },
      {
        path: "src/lib/pricing-health.ts",
        does: "Client-side helpers (HealthCheck, RecipePricingHealth, HEALTH_LABEL, HEALTH_BADGE_CLASS, fixHintForCheck) that normalize JSON returned by SQL functions recipe_pricing_health(recipe_id) and recipe_pricing_health_summary(). Drives all health badges.",
        layers: ["Guardrails / validation"],
        notes: "Header explicitly states 'Health is derived — never manually editable.' DB function is source of truth.",
        recommendation: "KEEP",
      },
    ],
  },
  {
    title: "2. Baseline cost ingestion",
    entries: [
      {
        path: "src/lib/server/kroger-core.ts",
        does: "Shared Kroger primitives: in-memory OAuth2 token cache (refreshes 60s before expiry), 429/503 backoff, ZIP→locationId resolution cached in app_kv for 30 days, per-unit price normalization (separates promo vs regular, emits quarantine signals), confidence scoring for SKU→ingredient_reference matches. Tokens never leave the module.",
        layers: ["Baseline cost ingestion", "Cost normalization"],
        notes: "Default ZIP 44202. Exports BOOTSTRAP_SEARCH_TERMS, getKrogerFetch, normalizeForScoring, normalizeKrogerPrice, resolveRunLocationId, scoreSkuMatch.",
        recommendation: "CENTRALIZE",
      },
      {
        path: "src/lib/server/kroger-ingest-internal.ts",
        does: "Cron-callable worker. Two modes: catalog_bootstrap (a–z + 0–9 sweep, writes kroger_sku_map only, resumable via kroger_bootstrap_progress, no price_history writes) and daily_update (only confirmed SKUs linked to inventory via ingredient_reference, writes per-unit normalized observations to price_history with promo flag + ingest_run_id, skips quarantined sizes / zero prices). Fatal aborts on OAuth failure or unresolved location.",
        layers: ["Baseline cost ingestion"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/kroger-pricing.functions.ts",
        does: "Phase 2 admin-callable signal-only Kroger integration. Disabled by default via app_kv.enable_kroger_ingest. Exits early if API keys missing. Writes only to price_history; never touches inventory_items.average_cost_per_unit, recipes, or quotes.",
        layers: ["Baseline cost ingestion"],
        notes: "Hard guarantee: 'NEVER mutates inventory_items / recipes / quotes.'",
        recommendation: "EXPOSE",
      },
      {
        path: "src/routes/api/public/hooks/kroger-daily-ingest.ts",
        does: "Public webhook entry that triggers the daily ingest worker (cron / external scheduler).",
        layers: ["Baseline cost ingestion"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/process-receipt.functions.ts",
        does: "AI Gateway OCR for receipts. Loads configurable threshold from app_kv.receipt_match_confidence_threshold (default 0.6). Extracts line items (item_name, quantity, unit, unit_price, total_price), runs match scoring against ingredient_reference/inventory_items; matches below threshold dropped to manual review queue with reason flag. Stores extracted_line_items on the receipt row.",
        layers: ["Baseline cost ingestion"],
        notes: "OCR is one-shot — re-run gated by `rerun` param. Does NOT itself update inventory.",
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/update-inventory-costs.functions.ts",
        does: "Reads a receipt row, iterates extracted_line_items with matched_inventory_id, updates inventory_items using receipt cost (uses receipt_date as observed_at). One of two paths that mutate inventory_items.average_cost_per_unit.",
        layers: ["Baseline cost ingestion", "Cost normalization"],
        notes: "Partial — re-implements weighted-average logic that SQL apply_po_to_inventory does for POs. Verify both paths produce same average.",
        recommendation: "CENTRALIZE",
      },
      {
        path: "src/lib/server-fns/process-purchase-order.functions.ts",
        does: "AI Gateway OCR for PO images → returns structured PO. Persistence handled elsewhere; SQL apply_po_to_inventory(_po_id) applies received POs to inventory + writes price_history (source='purchase_order').",
        layers: ["Baseline cost ingestion"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/process-sale-flyer.functions.ts",
        does: "OCR for supplier sale flyers; populates sale_flyers table (referenced by SQL get_active_flyer_for_supplier).",
        layers: ["Baseline cost ingestion"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/fred-pricing.functions.ts",
        does: "Pulls latest FRED observations using fred_series_map, matches to inventory via reference / synonyms / keywords, returns admin preview. Apply step updates inventory_items.average_cost_per_unit + last_receipt_cost, writes price_history (source='fred'), appends to national_price_snapshots (monthly), and recomputes cost on every recipe using each updated item.",
        layers: ["Baseline cost ingestion", "Pricing model"],
        notes: "One of the few paths that does mutate inventory_items — distinct from Kroger's signal-only stance.",
        recommendation: "EXPOSE",
      },
      {
        path: "src/lib/server-fns/bulk-refresh-fred.functions.ts",
        does: "Bulk refresh trigger over all active fred_series_map rows.",
        layers: ["Baseline cost ingestion"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/fred-mappings.functions.ts",
        does: "Admin CRUD over fred_series_map (series_id, label, unit, unit_conversion, match_keywords, priority).",
        layers: ["Baseline cost ingestion"],
        recommendation: "KEEP",
      },
      {
        path: "src/routes/hooks/national-prices-monthly.ts",
        does: "Cron entry that snapshots national prices monthly into national_price_snapshots.",
        layers: ["Baseline cost ingestion"],
        recommendation: "KEEP",
      },
    ],
  },
  {
    title: "3. Recipe cost calculation (helpers + UI)",
    description:
      "The authoritative recipe cost recompute lives in SQL recompute_recipe_cost(recipe_id), called from triggers trg_inventory_cost_changed, trg_recipe_servings_changed, trg_recipe_ing_changed and from fred-pricing after national updates. Frontend helpers below.",
    entries: [
      {
        path: "src/components/admin/CostBreakdownPanel.tsx",
        does: "Loads getCostBreakdown(referenceId) from cost-intelligence.functions.ts; renders per-source weight breakdown for one ingredient.",
        layers: ["Cost normalization"],
        recommendation: "EXPOSE",
      },
      {
        path: "src/lib/server-fns/cost-intelligence.functions.ts",
        does: "Admin-only Zod-validated server fns. Wraps SQL compute_internal_estimated_cost / propose_internal_cost_update / approve_cost_update / reject_cost_update / override_cost_update, plus list/search ingredient_reference and the cost queue.",
        layers: ["Cost normalization", "Guardrails / validation"],
        notes: "SQL guardrail: any internal cost change >±5% queues for review; manual cost is sacred and can never be overwritten by Kroger.",
        recommendation: "CENTRALIZE",
      },
      {
        path: "src/components/admin/CostHealthWidget.tsx",
        does: "Aggregate health stats: active recipes, servings=1 count, zero-cost recipe count, unlinked ingredient count, last receipt date.",
        layers: ["Guardrails / validation"],
        recommendation: "KEEP",
      },
      {
        path: "src/components/admin/PricingHealthPanel.tsx",
        does: "Per-recipe health checks via SQL recipe_pricing_health(recipe_id); renders pass/fail per check (resolution, units, density, waste, price, freshness).",
        layers: ["Guardrails / validation"],
        recommendation: "KEEP",
      },
    ],
  },
  {
    title: "4. Pricing model & quote application",
    entries: [
      {
        path: "src/lib/server-fns/recalc-quote-pricing.functions.ts",
        does: "Reads app_settings.markup_multiplier (default 3.0), iterates quote_items, recomputes unit_price = recipe.cost_per_serving * markup and total_price.",
        layers: ["Pricing model", "Quote application"],
        notes: "Uses single global markup_multiplier. Per-recipe markup_percentage (used by SQL compute_recipe_selling_price) is NOT honored here — divergence between SQL trigger trg_recipe_sync_pricing_columns and this server fn.",
        recommendation: "CENTRALIZE",
      },
      {
        path: "src/lib/server-fns/apply-national-floor.functions.ts",
        does: "Margin-safe quote re-pricing. For each ingredient on each recipe in the quote, computes effective unit cost = MAX(national_price_snapshot, recent_local_avg) via convertQty, then writes quote_items + quotes.subtotal/total. Read-only against source tables. Gated by app_kv.enable_national_pricing.",
        layers: ["Pricing model", "Quote application"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/quote-recipes.ts",
        does: "Pure helpers: filterRecipesForSelections (style/protein/allergen + pricing-status gate; never exposes recipes whose pricing_status !== 'valid') and pricePerGuestForRecipe used by pricing-test.tsx.",
        layers: ["Quote application", "Guardrails / validation"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/use-pricing-visibility.ts",
        does: "Reads app_kv.hide_public_pricing. Default = HIDE on public pages unless admin explicitly sets value to 'false'.",
        layers: ["Pricing model"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/national-pricing-activation.functions.ts",
        does: "Admin staging flow for activating a national-price month: status, preview, upsertStagingRows, activateNationalPrices (writes chosen month into app_kv.active_national_price_month consumed by floor pricing).",
        layers: ["Pricing model"],
        recommendation: "EXPOSE",
      },
      {
        path: "src/lib/server-fns/margin-reporting.functions.ts",
        does: "Backs MarginVolatilityChart; aggregates margin/quote pricing over time.",
        layers: ["Pricing model"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/price-volatility.functions.ts",
        does: "Deterministic volatility detector (admin notification only). Triggers when local 45-day avg deviates ±20% from current national snapshot, or month-over-month national change ≥15%. No mutations.",
        layers: ["Guardrails / validation"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/ingredient-coverage.functions.ts",
        does: "Three deterministic coverage indicators: global linkage % (recipe_ingredients → ingredient_reference), per-quote coverage, national snapshot coverage of ingredient_reference.",
        layers: ["Guardrails / validation"],
        recommendation: "EXPOSE",
      },
      {
        path: "src/lib/server-fns/receipt-kroger-diagnostics.functions.ts",
        does: "Cross-checks receipt-derived prices vs Kroger price observations for the same item; admin diagnostic view.",
        layers: ["Guardrails / validation"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/analyze-competitor-quote.functions.ts",
        does: "Uses recipe pricing as input for competitor quote analysis.",
        layers: ["Pricing model"],
        recommendation: "KEEP",
      },
      {
        path: "src/lib/server-fns/build-counter-quote.functions.ts",
        does: "Builds a counter-quote against an analyzed competitor quote using internal pricing.",
        layers: ["Pricing model", "Quote application"],
        recommendation: "KEEP",
      },
    ],
  },
  {
    title: "5. Admin pricing UI surfaces",
    entries: [
      { path: "src/routes/admin/cost-queue.tsx", does: "Review/approve/reject/override cost_update_queue (>±5% changes).", layers: ["Guardrails / validation"], recommendation: "KEEP" },
      { path: "src/routes/admin/ingredient-reference.tsx", does: "CRUD over ingredient_reference (canonical names, manual costs, weights, density).", layers: ["Cost normalization"], recommendation: "EXPOSE" },
      { path: "src/routes/admin/inventory.tsx", does: "inventory_items table + average-cost view.", layers: ["Cost normalization"], recommendation: "KEEP" },
      { path: "src/routes/admin/national-prices.tsx", does: "Staging + activation UI calling national-pricing-activation.", layers: ["Pricing model"], recommendation: "EXPOSE" },
      { path: "src/routes/admin/pricing-lab.tsx", does: "Sandbox: tweak markup/cost inputs, see price output (no writes).", layers: ["Pricing model"], recommendation: "KEEP" },
      { path: "src/routes/admin/pricing-lab.preview.tsx", does: "Read-only preview variant of pricing-lab.", layers: ["Pricing model"], notes: "Overlaps with pricing-lab.", recommendation: "LEGACY" },
      { path: "src/routes/admin/pricing-test.tsx", does: "Uses pricePerGuestForRecipe to validate per-tier pricing.", layers: ["Quote application"], recommendation: "KEEP" },
      { path: "src/routes/admin/pricing-visibility.tsx", does: "Toggles app_kv.hide_public_pricing.", layers: ["Pricing model"], recommendation: "KEEP" },
      { path: "src/routes/admin/pricing.national.tsx", does: "Older entry pointing to national-prices flow.", layers: ["Pricing model"], notes: "Verify vs national-prices.tsx.", recommendation: "LEGACY" },
      { path: "src/routes/admin/kroger-pricing.tsx", does: "Kroger ingest controls + run history.", layers: ["Baseline cost ingestion"], recommendation: "KEEP" },
      { path: "src/routes/admin/kroger-sku-review.tsx", does: "Confirm/reject SKU↔ingredient_reference matches (review_state).", layers: ["Baseline cost ingestion"], recommendation: "KEEP" },
      { path: "src/routes/admin/kroger-price-signals.tsx", does: "Charts the kroger_price_signals SQL view (inventory_cheap/expensive/stale flags).", layers: ["Guardrails / validation"], recommendation: "KEEP" },
      { path: "src/routes/admin/receipts.tsx", does: "Receipt list.", layers: ["Baseline cost ingestion"], recommendation: "KEEP" },
      { path: "src/routes/admin/receipts.review-matches.tsx", does: "Match-review queue for OCR'd receipt items below confidence threshold.", layers: ["Baseline cost ingestion"], recommendation: "KEEP" },
      { path: "src/routes/admin/receipt-kroger-diagnostics.tsx", does: "UI for receipt vs Kroger diagnostics fn.", layers: ["Guardrails / validation"], recommendation: "KEEP" },
      { path: "src/routes/admin/purchase-orders.tsx", does: "PO list; status 'received' triggers SQL apply_po_to_inventory.", layers: ["Baseline cost ingestion"], recommendation: "KEEP" },
      { path: "src/routes/admin/sales.tsx", does: "Sale-flyer list (consumed by SQL get_active_flyer_for_supplier).", layers: ["Baseline cost ingestion"], recommendation: "KEEP" },
      { path: "src/routes/admin/sale-flyers.$id.tsx", does: "Sale-flyer detail / review.", layers: ["Baseline cost ingestion"], recommendation: "KEEP" },
      { path: "src/routes/admin/auto-link-ingredients.tsx", does: "Bulk-link recipe_ingredients → ingredient_reference (gates pricing).", layers: ["Cost normalization"], recommendation: "KEEP" },
      { path: "src/routes/admin/synonyms.tsx", does: "Ingredient synonym management (used by FRED matching).", layers: ["Cost normalization"], recommendation: "KEEP" },
      { path: "src/routes/admin/servings-review.tsx", does: "Flags servings=1 recipes (cost-per-serving distortion).", layers: ["Guardrails / validation"], recommendation: "KEEP" },
      { path: "src/routes/admin/recipe-hub.tsx", does: "Recipe hub landing.", layers: ["Recipe cost calculation"], recommendation: "KEEP" },
      { path: "src/routes/admin/recipe-hub.$id.tsx", does: "Recipe editor; embeds PricingHealthPanel + CostBreakdownPanel.", layers: ["Recipe cost calculation"], recommendation: "KEEP" },
      { path: "src/components/PriceSparkline.tsx", does: "Per-item price_history mini chart.", layers: ["Pricing model"], recommendation: "KEEP" },
      { path: "src/components/admin/MarginVolatilityChart.tsx", does: "Margin reporting chart.", layers: ["Pricing model"], recommendation: "KEEP" },
      { path: "src/components/admin/FredMappingsManager.tsx", does: "FRED mapping admin UI.", layers: ["Baseline cost ingestion"], recommendation: "KEEP" },
      { path: "src/components/admin/FredPullPanel.tsx", does: "FRED pull-and-apply admin UI.", layers: ["Baseline cost ingestion"], recommendation: "KEEP" },
      { path: "src/components/admin/CoverageBadges.tsx", does: "Coverage indicator badges.", layers: ["Guardrails / validation"], recommendation: "KEEP" },
      { path: "src/components/employee/RecipeBreakdown.tsx", does: "Reads recipe cost & ingredient quantities for ops.", layers: ["Quote application"], recommendation: "KEEP" },
      { path: "src/components/employee/ShoppingList.tsx", does: "Shopping list driven by recipe ingredients + costs.", layers: ["Quote application"], recommendation: "KEEP" },
      { path: "src/components/quote/QuoteStepRecipes.tsx", does: "Quote builder step that consumes filtered recipes + tier prices.", layers: ["Quote application"], recommendation: "KEEP" },
      { path: "src/components/quote/QuoteStepTier.tsx", does: "Tier selection step for quote pricing.", layers: ["Quote application"], recommendation: "KEEP" },
      { path: "src/components/quote/QuoteStepAddons.tsx", does: "Add-on pricing step.", layers: ["Quote application"], recommendation: "KEEP" },
      { path: "src/components/quote/QuoteStepExtras.tsx", does: "Extras pricing step.", layers: ["Quote application"], recommendation: "KEEP" },
      { path: "src/components/quote/types.ts", does: "TIERS + SelectedRecipe types used across quote pricing.", layers: ["Quote application"], recommendation: "KEEP" },
      { path: "src/components/recipes/RecipeForm.tsx", does: "Recipe edit UI.", layers: ["Recipe cost calculation"], recommendation: "KEEP" },
      { path: "src/components/recipes/RecipeScaler.tsx", does: "Recipe scaler relies on convertQty for unit math.", layers: ["Unit conversion"], recommendation: "KEEP" },
      { path: "src/components/recipes/UnlinkedIngredientsReview.tsx", does: "Surfaces ingredients not linked to ingredient_reference (pricing gate).", layers: ["Cost normalization"], recommendation: "KEEP" },
      { path: "src/components/competitor/BulkCompetitorUpload.tsx", does: "Bulk competitor pricing import.", layers: ["Pricing model"], recommendation: "KEEP" },
    ],
  },
];

export const PRICING_INVENTORY_SQL_REFERENCE = [
  "compute_internal_estimated_cost(_kroger,_manual,_historical) → weighted estimate (40/40/20, redistributed if any source is null).",
  "propose_internal_cost_update(...) → diff vs current; auto-apply ≤5%, queue >5%; manual cost can never be overwritten by Kroger.",
  "approve_cost_update / reject_cost_update / override_cost_update → queue resolution; logs to access_audit_log; drafts a change_log_entries row when approved >5%.",
  "compute_recipe_selling_price(cost, markup_pct) → uses per-recipe markup_percentage else app_settings.markup_multiplier.",
  "trg_recipe_sync_pricing_columns → keeps calculated_cost_per_person and selling_price_per_person in sync on recipe write.",
  "recompute_quote_totals(_quote_id) → sums quote_items.total_price, applies quotes.tax_rate.",
  "apply_po_to_inventory(_po_id) → weighted-average update on PO receive + writes price_history.",
  "kroger_price_signals() view → flags inventory items as cheap/expensive/stale vs 30-day Kroger median.",
  "recipe_pricing_health_summary() → status + stale ingredient count per recipe.",
  "enforce_quote_revision_lock trigger → blocks edits within app_settings.revision_lock_days of event_date (admins bypass).",
];

export const PRICING_INVENTORY_FINDINGS = [
  "Two cost-mutation paths into inventory_items — update-inventory-costs.functions.ts (TS) and apply_po_to_inventory (SQL). Different averaging logic. Worth aligning.",
  "Two markup paths — SQL compute_recipe_selling_price honors per-recipe markup_percentage; recalc-quote-pricing.functions.ts only uses global app_settings.markup_multiplier. Quotes can disagree with recipes.",
  "No weight↔volume bridging in recipe-costing.ts — densities are not applied. ingredient_reference does carry density_g_per_ml used by SQL health checks.",
  "pricing-lab.preview.tsx and pricing.national.tsx look like older variants of pricing-lab.tsx and national-prices.tsx — flagged LEGACY for verification, not deletion.",
  "All cost-mutating writes go through audit/queue layer (cost_update_queue + access_audit_log) — guardrail any Item Cost Matrix should plug into.",
];
